name: Compile libbl602_wifi
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Build libbl602_wifi
      run: mkdir build && cd build && cmake -DUSE_CLANG=ON .. && make -j && cd ..
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libbl602_wifi
        path: build/src/bl602_wifi/libbl602_wifi.a
    